name: Lychee Link Checking

on:
  # Run on PRs targeting main that change content files.
  pull_request:
    branches: [main]
    paths: ['**/*.mdx?']
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  link-check:
    name: Lychee Link Checking
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ !github.event.pull_request.draft }}

    steps:
    - name: Check out repo
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Get changed content files
      id: changed-mdx-files
      uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
      with:
        files: |
          **.mdx

    - name: Run Lychee
      uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
      with:
        fail: false
        failIfEmpty: false
        format: markdown
        jobSummary: true
        args: >
          -c lychee.toml
          --root-dir "$(pwd)/main"
          ${{ steps.changed-mdx-files.outputs.all_changed_files }}

    - name: Clean output file
      run: sed -i "s,file://$(pwd)/main,," lychee/out.md

    - name: Comment on PR with link check results
      uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
      with:
        path: lychee/out.md
        message: |
          {{{content}}}

          *Run on commit ${{ github.sha }}.*
