name: Update SDK library versions

on:
  schedule:
    - cron: '0 13 * * 1-5' # Mon-Fri at 1pm UTC (9am ET)
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Fetch latest SDK releases and update libraries.mdx
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # The first line of the file is a JS variable declaration. The last
          # line is a semicolon. Everything between is valid JSON.
          FILE="main/snippets/sdks/versions.mdx"

          # Remove first and last lines and generate updated JSON:
          sed '1d;$d' $FILE | python3 scripts/fetch-sdk-versions.py > output.json

          # Add first/last line back and save to original file:
          sed '1s;^;export const sdkCardInfo =\n;' output.json | sed '$s;$;\n\;;' > $FILE
          rm output.json

      - name: Open or update PR
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          sign-commits: true
          title: "chore: update SDK library versions"
          commit-message: "chore: update SDK library versions"
          branch: automated/sdk-version-update
          body: "Automated daily sync of SDK versions and release dates."
