name: Vale

on:
  pull_request:
    paths:
      - 'main/**/*.md'
      - 'main/**/*.mdx'
      - 'main/**/*.jsx'
      - 'auth4genai/**/*.md'
      - 'auth4genai/**/*.mdx'
      - 'auth4genai/**/*.jsx'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Install mdx2vast
        run: npm install -g mdx2vast

      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          vale_flags: "--glob=!{main/docs/fr-ca/*,main/docs/ja-jp/*}"
          fail_on_error: true
          filter_mode: nofilter
